# 匈牙利算法(指派问题）

算法解释：https://blog.csdn.net/qq_42178122/article/details/116196071

及匈牙利算法用于解开销矩阵的最小开销

使用scipy库实现：（算法来源https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html#scipy.optimize.linear_sum_assignment）

In [2]:
from scipy.optimize import linear_sum_assignment
import numpy as np

cost =np.array([[4,1,3],[2,0,5],[3,2,2]])
row_ind,col_ind=linear_sum_assignment(cost)
print(row_ind)  # 开销矩阵对应的行索引
print(col_ind)  # 对应行索引的最优指派的列索引
print(cost[row_ind,col_ind])  # 提取每个行索引的最优指派列索引所在的元素，形成数组
print(cost[row_ind,col_ind].sum())  # 数组求和

[0 1 2]
[1 0 2]
[1 2 2]
5


## 非线性整数规划

对于非线性整数规划，可使用蒙特卡洛法进行估算：

$\max z = x_1^2+x_2^2+3x_3^2+4x_4^2+2x_5^2-8x_1-2x_2-3x_3-x_4-2x_5$

$s.t.=
\begin {cases}0\le x_i\le99, \\
x_1+x_2+x_3+x_4+x_5\le400, \\
x_1+2x_2+2x_3+x_4+6x_5\le800, \\
2x_1+x_2+6x_3\le200, \\
x_3+x_4+5x_5\le500.
\end {cases}$

In [12]:
import numpy as np


def check(x):
    if x.sum() > 400:
        return False
    if x[0]+2*x[1]+2*x[2]+x[3]+6*x[4] > 800:
        return False
    if 2*x[0]+x[1]+6*x[2]>200:
        return False
    if x[2]+x[3]+5*x[4]>500:
        return False
    return True


def get_radom():
    x = np.random.randint(100, size=5)
    while not check(x):
        x = get_radom()
    return x


lim = 10**6
ans = -1
ans_x = []

for i in range(lim):
    num = get_radom()
    #print(num)
    #print(num[0]**2+num[1]**2+3*num[2]**2+4*num[3]**2+2*num[4]**2-8*num[0]-2*num[1]-3*num[2]-num[3]-2*num[4])
    if(num[0]**2+num[1]**2+3*num[2]**2+4*num[3]**2+2*num[4]**2-8*num[0]-2*num[1]-3*num[2]-num[3]-2*num[4]>ans):
        ans = num[0]**2+num[1]**2+3*num[2]**2+4*num[3]**2+2*num[4]**2-8*num[0]-2*num[1]-3*num[2]-num[3]-2*num[4]
        ans_x = num
    if i % 100000 == 0:
        print(i)
print('x=',ans_x)
print('ans=',ans)

0
100000
200000
300000
400000
500000
600000
700000
800000
900000
x= [46 92  0 99 78]
ans= 61145
